# Generated by Django 5.1.2 on 2024-11-09 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_book_language_bookinstance_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinstance',
            name='language',
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ManyToManyField(help_text='Seleccione un idioma para este libro', to='catalog.language'),
        ),
    ]
